services:
  front:
    container_name: dev-transcript-front
    build: 
      context: ./front
      dockerfile: Dockerfile
      target: dev
    ports:
      - "${FRONT_PORT}:5173"
    env_file:
      - .env
    volumes:
      - ./front:/app
  db-dev:
    container_name: dev-transcript-db
    build: ./db
    ports:
      - "${DB_PORT}:8090"
    volumes:
      - ./db/pb_migrations/:/pb_migrations
      - ./db/pb_data/:/pb_data/
  back-dev:
    container_name: dev-transcript-back
    build: 
      context: ./back/
      target: "dev"
    ports:
      - "${BACK_PORT}:3000"
    depends_on:
      - db-dev
      - postgresql
      - temporal-dev
    volumes:
      - ./back/src:/app/src
    env_file:
      - .env
  # temporal has no postgres_host env variable, so we need to name the postgres service postgresql
  postgresql:
    restart: unless-stopped
    container_name: dev-transcript-postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:13
    env_file: .env
    volumes:
      - ./postgres/data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  temporal-dev:
    restart: unless-stopped
    container_name: dev-transcript-temporal
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DB=postgresql
      - DB_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=postgresql
      - TEMPORAL_ADDRESS=temporal-dev:7233
      - LOG_LEVEL=info
    image: temporalio/auto-setup:latest
    env_file: .env
  temporal-ui-dev:
    restart: unless-stopped
    container_name: dev-transcript-temporal-ui
    depends_on:
      - temporal-dev
    environment:
      - TEMPORAL_ADDRESS=temporal-dev:7233
    image: temporalio/ui:latest
    env_file: .env
    ports:
      - ${TEMPORAL_UI_PORT-4004}:${TEMPORAL_UI_PORT-4004}